/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#78dc77',
        'inverse-primary': '#a8c8ff',
        'secondary-fixed': '#cae6ff',
        'tertiary-container': '#004e11',
        'primary-fixed': '#d5e3ff',
        'on-surface': '#181c1e',
        'secondary-fixed-dim': '#8ccdff',
        'error-container': '#ffdad6',
        'on-primary-container': '#84b0f7',
        'on-tertiary-fixed': '#002204',
        'surface-container-low': '#f1f4f7',
        'outline-variant': '#c3c6d2',
        surface: '#f7fafd',
        background: '#f7fafd',
        'on-secondary-fixed-variant': '#004b6f',
        'tertiary-fixed': '#94f990',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e3e6',
        'surface-container': '#ebeef1',
        primary: '#002c5a',
        'on-secondary': '#ffffff',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#2e5fa0',
        'on-secondary-fixed': '#001e2f',
        tertiary: '#003509',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eef1f4',
        'on-background': '#181c1e',
        outline: '#737781',
        'on-tertiary-container': '#61c462',
        'on-primary-fixed': '#001b3c',
        'on-primary': '#ffffff',
        'surface-dim': '#d7dadd',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#005313',
        'surface-bright': '#f7fafd',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#a8c8ff',
        'secondary-container': '#58bcfd',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e5e8eb',
        secondary: '#006492',
        'primary-container': '#004282',
        'on-surface-variant': '#424750',
        'on-secondary-container': '#004a6d',
        'on-primary-fixed-variant': '#0a4687',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.25rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
